### ISSUE TITLE
Can't handle WebSocket connection

### ISSUE THREAD

**Issue by bonyfr** [mitre/HTTP-Proxy-Servlet#100] opened 2016-09-16 14:51 UTC
I'm trying to use your reverse proxy, but it doesn't work with Websocket connection.

Do you have some idea to do it ?

Eric

**Comment by dsmiley** [comment] 2016-09-19 11:58
Sorry I have no idea.  If you work on it and submit a PR, I would gladly take a look.

FYI also asked in #88

**Comment by dsmiley** [comment] 2016-09-19 11:59
This is really a duplicate of that issue so I'll close it.

**Closed by dsmiley** 2016-09-19 11:59 UTC
Labels: enhancement
