### ISSUE TITLE
Proxy should copy response headers for redirect

### ISSUE THREAD

**Issue by cd0304** [mitre/HTTP-Proxy-Servlet#51] opened 2015-03-24 10:04 UTC
in html cookie ,it have connect.sid, this is session use in my node.js server， but use this proxy, my broswer cookie ,this connect.sid will change every one.

**Comment by cd0304** [comment] 2015-03-24 10:54
my cookie is :

!Proxy!dswlJSESSIONID=MWzgVRBKT1Mm50KjH2J1Lrp1GS7cMM7pzhDR0b2pMTTp10mzx0h
h!973736762; gddsCurrentPage=home4.main; gddsFocushome4.main=btn_3; gddsFocuscat
egory.kexue.main=btn_0; category.kexue.mainpage=1; gddsFocuscategory.meishu.main
=btn_0; category.meishu.mainpage=1; connect.sid=s%3AfKW7l4E5IohDwxz6bAArMRYu.%2B
f330dqw6fdWcbQBmxJevXN%2B1LYqvKrGUfeDB%2B3zJhM

but use proxy ,my server reveive this cookie:
cookie:JSESSIONID=mH2yVRBZVNvjbj40pSnkzlgnvN1t2DTGcGqmSP1z20Cj8FrC25HQ!-775714485

other cookie miss

**Comment by dsmiley** [comment] 2015-03-24 13:08
I'm having difficulty understanding what the problem is.  Can you please try and clearly state what you think the expected behavior of the proxy is, and then say what it does?

**Comment by cd0304** [comment] 2015-03-25 11:33
I debug in my browser,i find this problem

my node.js server will set the cookie : connect.sid ,this is the session use in my server

but use proxy , connect.sid  will send to brower , but the connect.sid expire time is set 1970 year 1 month 1 day 8:00:10 。so the brower do not send teh connect.sid to server next time.
i do not know why the expire time would set that.

**Comment by dsmiley** [comment] 2015-03-25 12:14
Hmm; perhaps the servlet engine you are using did this automatically?  As you can see, the proxy certainly isn't.

**Comment by cd0304** [comment] 2015-03-26 03:27
i remove the function call :copyProxyCookie, Seems to be working all right, 
why must replace the cookie ,  now ,i directly transfer cookie info ,do not change anything.

**Comment by flytreeleft** [comment] 2015-05-10 07:22
Actually, I found that SESSIONID or other Cookie which comes from remote server will be lost if the proxied url was redirected to another one. 

At line 274 in [ProxyServlet.java](https://github.com/mitre/HTTP-Proxy-Servlet/blob/master/src/main/java/org/mitre/dsmiley/httpproxy/ProxyServlet.java#L274) was mentioned  whether copy response headers or not, my answer is **YES**, and must be copied before invoking ```HttpServletResponse.sendRedirect(String)``` (the committed response cannot be changed).

Why we need to do this? 

For example, there is a web site needs to login first, and you access the url "http://localhost/home.action" directly, it will redirect you to "http://localhost/login.action". Before redirecting to "/login.action", it always put "Set-Cookie: JSESSIONID=xxxx" in header. The correct _JSESSIONID_ must be sent to the server when logining, because the server had put a _Private Key_ in session and the password was encrypted by the Key before sending login request. If the response headers wasn't copied to HttpServletResponse before ```HttpServletResponse.sendRedirect(targetUri)```, you will stay in "/login.action" forever :(

**Comment by dsmiley** [comment] 2015-05-10 14:04
Ah; makes sense.   Pull requests (w/ test) welcome :-)  I'm very busy now so I'm not sure when I'll get to it.

**Comment by flytreeleft** [comment] 2015-05-13 05:45
OK, I will submit a PR as soon as possible :-)

**Closed** 2015-05-15 04:22 UTC
Labels: bug
