### ISSUE TITLE
Connection reset exception

### ISSUE THREAD

**Issue by alpha34** [mitre/HTTP-Proxy-Servlet#16] opened 2013-09-27 16:05 UTC
Hello,

I have been testing this servlet for a requirement we have and it has been fairly stable except for the following one issue. 

This happens intermittently and when we see this error, the servlet hangs (it continues to receive requests but does not send a response back to the client). I am using this servlet to forward requests that come over a HTTPS pipe to tomcat to various end points over HTTP after some pre-processing (client --> https --> tomcat proxy servlet --> http --> endpoints).

Environment - Tomcat 6.0.33/Scientific Linux 5.9

Exception -
ClientAbortException: javax.net.ssl.SSLException: Connection has been shutdown.: javax.net.ssl.SSLException:java.net.SocketException:Connection reset.

at org.apache.catalina.connector.OutputBuffer.realWriteBytes()
at org.apache.tomcat.util.buf.ByteChunk.flushBuffer()
at org.apache.catalina.connector.OutputBuffer.doFlush()
at org.apache.catalina.connector.OutputBuffer.close()
at org.apache.catalina.connector.CoyoteOutputStream.close()
at com.acme.ProxyServlet.closeQuietly()

Please respond with any suggestions.

**Comment by krishna81m** [comment] 2015-02-03 01:46
Why wouldn't the servlet respond back to the client in this case and what happens to this connection?

**Comment by dsmiley** [comment] 2015-10-08 16:05
Closing as duplicate of #23 (closed).

**Closed by dsmiley** 2015-10-08 16:05 UTC
Labels: duplicate
